
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 09 13:20:44 CST 2013
//----------------------------------------------------

package nuevo_compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _negacion = 41;
  public static final int _new = 40;
  public static final int _suma = 43;
  public static final int _exit = 30;
  public static final int _menorigual = 49;
  public static final int _main = 11;
  public static final int _resta = 44;
  public static final int _this = 36;
  public static final int _redondoizq = 15;
  public static final int _menorque = 48;
  public static final int _println = 29;
  public static final int _return = 21;
  public static final int _corcheteder = 18;
  public static final int _diferentea = 46;
  public static final int _true = 38;
  public static final int _coma = 22;
  public static final int _mayorigual = 50;
  public static final int _igual = 32;
  public static final int _cuadradoizq = 13;
  public static final int _void = 10;
  public static final int _import = 2;
  public static final int _class = 7;
  public static final int _else = 25;
  public static final int _TString = 12;
  public static final int _read = 35;
  public static final int _division = 45;
  public static final int _boolean = 23;
  public static final int _public = 8;
  public static final int EOF = 0;
  public static final int _redondoder = 16;
  public static final int error = 1;
  public static final int _or = 52;
  public static final int _in = 33;
  public static final int _asterisco = 4;
  public static final int _length = 37;
  public static final int _puntoasterisco = 54;
  public static final int _System = 27;
  public static final int _punto = 3;
  public static final int _numero = 34;
  public static final int _if = 24;
  public static final int _cuadradoder = 14;
  public static final int _id = 6;
  public static final int _while = 26;
  public static final int _corcheteizq = 17;
  public static final int _implements = 20;
  public static final int _out = 28;
  public static final int _extends = 19;
  public static final int _iguala = 47;
  public static final int _mayorque = 51;
  public static final int _and = 53;
  public static final int _false = 39;
  public static final int _puntoycoma = 5;
  public static final int _TInt = 31;
  public static final int _static = 9;
  public static final int _String = 42;
}

